CREATE DATABASE escola;
USE escola;


CREATE TABLE alunos(
`ALUNO_ID` INT (11) AUTO_INCREMENT PRIMARY KEY,
`NOME_ALUNO` VARCHAR (100) NOT NULL,
`DATA_NASCIMENTO` DATE NOT NULL,
`ENDERECO_ALUNO` VARCHAR (255),
`TELEFONE_ALUNO` VARCHAR(15),
`EMAIL_ALUNO` VARCHAR(100) UNIQUE
);

CREATE TABLE professores(
`PROFESSOR_ID` INT AUTO_INCREMENT PRIMARY KEY,
`NOME_PROFESSOR` VARCHAR(100) NOT NULL,
`ESPECIALIDADE` VARCHAR(100),
`ENDERECO_PROFESSOR` VARCHAR(255),
`TELEFONE_PROFESSOR` VARCHAR(15),
`EMAIL_PROFESSOR` VARCHAR(100) UNIQUE
);

CREATE TABLE cursos(
`CURSO_ID` INT AUTO_INCREMENT PRIMARY KEY,
`NOME_CURSO` VARCHAR(100) NOT NULL,
`DESCRICAO` TEXT, #TEXT É A MESMA COISA QUE VARCHAR, SÓ QUE SEM O LIMITE DE CARACTERES
`CARGA_HORARIA` INT NOT NULL
);

CREATE TABLE matriculas(
`MATRICULAS_ID` INT AUTO_INCREMENT PRIMARY KEY,
`ALUNO_ID` INT,
`CURSO_ID` INT,
`DATA_MATRICULA` DATE NOT NULL,
FOREIGN KEY (ALUNO_ID) REFERENCES alunos(ALUNO_ID),
FOREIGN KEY (CURSO_ID) REFERENCES cursos(CURSO_ID) 
);

CREATE TABLE aulas(
`AULA_ID` INT AUTO_INCREMENT PRIMARY KEY,
`CURSO_ID` INT,
`PROFESSOR_ID` INT,
`DATA_AULA` DATE NOT NULL,
`HORARIO` TIME NOT NULL,
FOREIGN KEY (CURSO_ID) REFERENCES cursos(CURSO_ID),
FOREIGN KEY (PROFESSOR_ID) REFERENCES professores(PROFESSOR_ID) 
);  

INSERT INTO alunos (NOME_ALUNO, DATA_NASCIMENTO, ENDERECO_ALUNO, TELEFONE_ALUNO, EMAIL_ALUNO) VALUES
('Peter William', '2003-09-13', 'Rua Summoners Rift, 194', '(41) 971942815', 'league_pgkbp@gmail.com'),
('Roberter Iri', '2003-06-12', 'Rua Jerônimo, 973', '(41) 728342834', 'money@gmail.com');

INSERT INTO professores (NOME_PROFESSOR, ESPECIALIDADE, ENDERECO_PROFESSOR, TELEFONE_PROFESSOR, EMAIL_PROFESSOR) VALUES
('Pedro Guilherme', 'Geografia', 'Avenida Abyss, 532', '(41) 281763827', 'league_legends@gmail.com'), 
('Nathan Cs', 'Física', 'Avenida C, 532', '(41) 192808173', 'counter_strike@gmail.com');

INSERT INTO cursos (NOME_CURSO, DESCRICAO, CARGA_HORARIA) VALUES
('Geografia', 'Curso de Geografia para quem não faz Geografia', 220),
('Física', 'Curso de Física Avançada focada na eletricidade', 120);

INSERT INTO matriculas(ALUNO_ID, CURSO_ID, DATA_MATRICULA) VALUES
(1, 1, '2024-02-24'),
(2, 2, '2023-09-18');

INSERT INTO aulas(CURSO_ID, PROFESSOR_ID, DATA_AULA, HORARIO) VALUES
(1, 1, '2024-09-04', '09:00:00'),
(2, 2, '2024-09-05', '11:00:00');

SELECT * FROM alunos;
SELECT c.NOME_CURSO AS cursos, p.NOME_PROFESSOR AS PROFESSOR
FROM aulas a
JOIN cursos c ON a.CURSO_ID = c.CURSO_ID
JOIN PROFESSORES p ON a.PROFESSOR_ID = p.PROFESSOR_ID;

SELECT a.NOME_ALUNO AS alunos, c.NOME_CURSO AS cursos, m.DATA_MATRICULA
FROM matriculas m
JOIN alunos a ON m.ALUNO_ID = a.ALUNO_ID
JOIN cursos c ON m.CURSO_ID = c.CURSO_ID
WHERE a.NOME_ALUNO = 'Peter William';